apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-config
  namespace: observability
data:
  fluent-bit.conf: |
    [SERVICE]
        Flush        1
        Log_Level    info
        Parsers_File parsers.conf
    [INPUT]
        Name             tail
        Path             /var/log/app/*.log
        Tag              sg-intranet
        Refresh_Interval 5
        Parser           json
    [OUTPUT]
        Name                es
        Match               *
        Host                elasticsearch.observability.svc.cluster.local
        Port                9200
        Index               sg-intranet-logs
        Suppress_Type_Name  On

  parsers.conf: |
    [PARSER]
        Name   json
        Format json