apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: sg-intranet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: "sg"
            - name: POSTGRES_PASSWORD
              value: "sg"
            - name: POSTGRES_DB
              value: "sg_intranet"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
      volumes:
        - name: postgres-storage
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: sg-intranet
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432