apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: observability
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'sg-intranet-backend'
        static_configs:
          - targets: ['backend.sg-intranet.svc.cluster.local:8000']
        metrics_path: '/metrics'